name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Lightsail
        env:
          HOST: ${{ secrets.LIGHTSAIL_HOST }}
          USERNAME: ${{ secrets.LIGHTSAIL_USER }}
          KEY: ${{ secrets.LIGHTSAIL_KEY }}
          DEST_PATH: ${{ secrets.LIGHTSAIL_PATH }}
        run: |

          mkdir -p ~/.ssh
          echo "${KEY}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rm -r dist/
          npm run build

          echo "Copying files..."
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -rv package.json package-lock.json $USERNAME@$HOST:$DEST_PATH/
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -rv dist/* $USERNAME@$HOST:$DEST_PATH/dist/

          echo "Restart PM2..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USERNAME@$HOST "
            cd $DEST_PATH
            npm install
            
            pm2 restart falcon-frontend || pm2 start "npm run preview --port 4000" --name "falcon-frontend"
          "

          echo "Deploy completed."
