name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.LIGHTSAIL_HOST }}
          USERNAME: ${{ secrets.LIGHTSAIL_USER }}
          KEY: ${{ secrets.LIGHTSAIL_KEY }}
          DEST_PATH: ${{ secrets.LIGHTSAIL_PATH }}
        run: |

          mkdir -p ~/.ssh
          echo "${KEY}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Copying files..."
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -rv package.json package-lock.json $USERNAME@$HOST:$DEST_PATH/
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -rv dist/* $USERNAME@$HOST:$DEST_PATH/dist/

          echo "Restart PM2..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USERNAME@$HOST "
            cd $DEST_PATH
            npm install
            rm -r dist/
            npm run build
            pm2 delete falcon-frontend || true
            pm2 start 'npm run preview' --name 'falcon-frontend'
          "

          echo "Deploy completed."
